name: Setup
description: Setup the environment

inputs:
  node-version:
    description: The version of node.js
    required: false
    default: "18"

runs:
  using: composite
  steps:
    - name: Install bun
      uses: oven-sh/setup-bun@v1

    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: "https://registry.npmjs.org"

    - name: Install pnpm
      run: corepack enable
      shell: bash

    - name: Install
      run: bun install --frozen-lockfile
      shell: bash
