name: Setup
description: Setup the environment

inputs:
  node-version:
    description: The version of node.js
    required: false
    default: "24"

runs:
  using: composite
  steps:
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: "https://registry.npmjs.org"

    - name: Setup pnpm
      uses: pnpm/action-setup@v4

    - name: Setup bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Install
      run: pnpm install --frozen-lockfile
      shell: bash
