packages:
  - website
  - packages/*
allowBuilds:
  esbuild: false
  msw: false
  sharp: false
  workerd: false
ignoreWorkspaceRootCheck: true
minimumReleaseAgeExclude:
  - '@astrojs/markdown-satteri@0.3.2'
  - astro@7.0.2
strictPeerDependencies: true
