packages:
  - website
  - packages/*

allowBuilds:
  esbuild: false
  msw: false
  sharp: false
  workerd: false

ignoreWorkspaceRootCheck: true

minimumReleaseAgeExclude:
  - '@floating-ui/core@1.8.0'
  - '@floating-ui/dom@1.8.0'
  - '@floating-ui/utils@0.2.12'

strictPeerDependencies: true
