name: CI

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

env:
  FORCE_COLOR: 1

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      - name: Lint
        run: pnpm run lint

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      - name: Build
        run: pnpm run build
