name: CI

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

env:
  FORCE_COLOR: 1

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      - name: Lint
        run: bun run lint

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      - name: Build
        run: bun run build

  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      deployments: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      - name: Build
        run: bun run build

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_PAGES_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: aria-ui
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          workingDirectory: website/dist
          directory: .
