name: Release

on:
  push:
    branches:
      - master

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    permissions:
      pull-requests: write
      contents: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: ./.github/actions/setup

      - name: Create Release Pull Request
        id: changesets
        uses: changesets/action@ae32849d5ba541f9ae29e40e22a623bc13562f51 # v2.1.2
        with:
          version-script: pnpm run ci:version
          publish-script: pnpm run ci:publish
          commit-message: 'chore: version packages'
          pr-title: 'chore: version packages'
          create-github-releases: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
